server:
  port: 8081

spring:
  profiles:
    active: dev
  web:
    resources:
      # 静态资源映射路径（指定的目录及其所有子目录，指定的目录对应URL的根目录）
      static-locations:
        - classpath:/web/staticRoot/

lavender:
  test-helper:
    server-port: ${server.port}
    proxy-pass-url-prefix: http://localhost:8080
